#!/usr/bin/env node

"use strict";

const fs = require("fs");

const pkg = JSON.parse(fs.readFileSync(process.argv[2]));

pkg.private = false;

fs.writeFileSync(process.argv[3], JSON.stringify(pkg, null, 2));
