#!/usr/bin/env node

"use strict";

/* eslint-disable no-console */

//
// Safety harness...
//

class Fatal extends Error {
  constructor(name, message) {
    super(message);
    this.name = "Fatal";
  }
}

process.on("uncaughtException", (ex) => {
  if (ex instanceof Fatal) {
    process.stderr.write(`${ex.message}\n`);
    process.exit(1);
  }
  else {
    throw ex;
  }
});

//
// Actual logic
//

const { execFile } = require("child_process");

execFile("git", ["status", "--porcelain"], (error, status) => {
  if (error) {
    throw error;
  }

  //
  // The describe command here uses --always. We are using this because when
  // running the test suite on Travis the git clone is shallow and has no tags.
  // So the describe command without --always fails. We could disable depth so
  // that the clone is complete but that seems wasteful.
  //
  // Right now we do not do releases through Travis so releases will always have
  // the benefit of a tag. If we do releases from Travis one day, then we can
  // set depth to something sensible if the default is not enough.
  //
  // Upshot: the build info is not the place from which to get a version number.
  //
  execFile("git", ["describe", "--match", "v*", "--always"],
           (descError, desc) => {
             if (descError) {
               throw descError;
             }

             desc = desc.trim();

             if (status.length !== 0) {
               desc += "-unclean";
             }

             console.log(`\
module.exports = {
  desc: "${desc}",
  date: "${new Date().toISOString()}",
};
`);
           });
});
